classdef FigureResizeHelper < matlab.unittest.TestCase
    % Tests for figure resize helper geometry

    %   Copyright 2026 The MathWorks Inc.


    %% Unit Test
    methods (Test)

        function testResizeEdgeDetection(testCase)

            pos = [100 100 200 150];
            borderWidth = 6;

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([100 249], pos, borderWidth), ...
                "top-left")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([299 249], pos, borderWidth), ...
                "top-right")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([100 100], pos, borderWidth), ...
                "bottom-left")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([299 100], pos, borderWidth), ...
                "bottom-right")

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([100 150], pos, borderWidth), ...
                "left")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([299 150], pos, borderWidth), ...
                "right")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([150 249], pos, borderWidth), ...
                "top")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([150 100], pos, borderWidth), ...
                "bottom")

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([150 150], pos, borderWidth), ...
                "")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizeEdge([99 150], pos, borderWidth), ...
                "")

        end %function


        function testResizePointerMapping(testCase)

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("left"), "left")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("right"), "right")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("top"), "top")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("bottom"), "bottom")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("top-left"), "topl")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("top-right"), "topr")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("bottom-left"), "botl")
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.getResizePointer("bottom-right"), "botr")

            testCase.verifyTrue(wt.utility.FigureResizeHelper.isResizePointer("topl"))
            testCase.verifyFalse(wt.utility.FigureResizeHelper.isResizePointer("arrow"))

        end %function


        function testResizePositionByEdge(testCase)

            pos = [100 100 200 150];
            bounds = [1 1 500 400];
            minSize = [50 40];

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [20 0], "right", bounds, minSize), ...
                [100 100 220 150])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [-20 0], "left", bounds, minSize), ...
                [80 100 220 150])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [0 30], "top", bounds, minSize), ...
                [100 100 200 180])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [0 -30], "bottom", bounds, minSize), ...
                [100 70 200 180])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [20 30], "top-right", bounds, minSize), ...
                [100 100 220 180])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [-20 -30], "bottom-left", bounds, minSize), ...
                [80 70 220 180])

        end %function


        function testResizeMinimumSizeClamping(testCase)

            pos = [100 100 200 150];
            bounds = [1 1 500 400];
            minSize = [120 80];

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [150 0], "left", bounds, minSize), ...
                [180 100 120 150])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [0 100], "bottom", bounds, minSize), ...
                [100 170 200 80])

        end %function


        function testResizeBoundsClamping(testCase)

            pos = [100 100 200 150];
            bounds = [1 1 350 300];
            minSize = [50 40];

            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [500 0], "right", bounds, minSize), ...
                [100 100 251 150])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [0 500], "top", bounds, minSize), ...
                [100 100 200 201])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [-500 0], "left", bounds, minSize), ...
                [1 100 299 150])
            testCase.verifyEqual(...
                wt.utility.FigureResizeHelper.calculateResizedPosition(...
                pos, [0 -500], "bottom", bounds, minSize), ...
                [100 1 200 249])

        end %function

    end %methods

end %classdef
