%%
appdesigner.customcomponent.configureMetadata(which("wt.ButtonGrid"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.CheckboxList"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.ColorSelector"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.DatetimeSelector"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.FileSelector"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.ListSelector"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.ListSelectorTwoPane"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.PasswordField"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.ProgressBar"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.SliderCheckboxGroup"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.SliderSpinner"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.TaskStatusTable"))
%%
appdesigner.customcomponent.configureMetadata(which("wt.Toolbar"))